Accessibility feature
fauziyahzeeyah/port-folio-mobile pull request #17
Opened 2022-12-23 14:26 UTC by fauziyahzeeyah

-  Add formData to local storage
-  Update styles
-  Corrected ESlint errors

2022-12-23 15:58 UTC, Favourezeugwa reviewed
## STATUS: REQUIRES CHANGES 🚦 ⚠️ ♻️ 

Hi @fauziyahzeeyah , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-brianna](https://user-images.githubusercontent.com/99246359/201470450-173d4ea7-fe78-470e-a872-142a58b56294.gif)


## Highlights 💯 
- No Linter errors ✔️
- Descriptive Pull request summary✔️
- Good commit messages ✔️
- Professional Readme file ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-23 15:58 UTC, Favourezeugwa commented on js/local-storage.js
> +});
- I don't think data entered in your form is being saved to the local storage.  Can we fix this?? 🤗 

Here is what i could see on my browser after cloning your repo 👇🏽 

![empt](https://user-images.githubusercontent.com/99246359/209363690-4054217e-d3f0-4191-bb84-ac3fa74731d3.PNG)

2022-12-24 09:34 UTC, tufoinnkuo10 requested changes
Hi @Team
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-12-24 09:34 UTC, tufoinnkuo10 commented on js/local-storage.js
> +  let message = '';
- [ ] great job. Please ensure that After filling the form, and not submitting it, the entered values should be saved in the browser. When the user loads the page, the code checks if there's any saved data in the local storage and if so the input fields are pre-filled with the data.

2022-12-24 10:47 UTC, binhussen approved these changes
Hi @fauziyahzeeyah , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-24 11:02 UTC, merged